name: Build and Deploy to EKS on Fargate

on:
  push:
    branches: [ main ]
    
jobs:
  build-and-deploy:
     name: Build and Push to ECR
     runs-on: ubuntu-latest
     
     env:
       AWS_REGION: us-east-1
       EKS_CLUSTER_NAME: demo
     
     steps:
     - name: Checkout
       uses: actions/checkout@v3
       
     - name: Set up JDK 19
       uses: actions/setup-java@v1
       with:
         java-version: 19
         
     - name: Set up Apache Maven
       uses: actions/setup-java@v1
       with:
         java-version: 19
         maven-version: 3.x
         
     - name: Build and Package the Application
       run: mvn clean package -DskipTests
       
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ env.AWS_REGION }}
         
     - name: Provision cluster
       uses: aws-actions/amazon-eks-fargate@v0.1
         
     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1
       
     - name: Automatic Tagging of Releases
       id: increment-git-tag
       run: |
         bash ./build/git_update.sh -v patch
         
     - name: Build, Tag, and Push the Image to Amazon ECR
       id: build-image
       env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         ECR_REPOSITORY: demo-app
         IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
       run: |
         docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
         echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

     - name: Setup kubeconfig
       id: setup-kubeconfig
       run: |
         aws eks --region us-east-1 update-kubeconfig --name demo      
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Log in to Amazon EKS
      run: |
        echo Logging in to Amazon EKS…
        aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $AWS_CLUSTER_NAME

    - name: Build and push Docker image
      run: |
        echo Build completed on `date`
        echo Pushing the Docker image…
        docker push $AWS_ACCOUNT_ID.dkr.ecr $AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

    - name: Update kubeconfig
      run: |
        echo Push the latest image to cluster
        aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $AWS_CLUSTER_NAME

    - name: Apply deployment.yaml
      run: kubectl apply -f eks_cicd/deployment.yaml 

    - name: Restart deployment
      run: kubectl rollout restart -f eks_cicd/deployment.yaml
